name: geo_fence
description: "A showcase project with provider and location."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-219.0.dev
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Local Storage
  hive: ^2.2.3
  hive_generator: ^2.0.1

  # Location
  location:
  geocoding:
  geolocator:
  permission_handler:

  # Notification
  elegant_notification:

  path_provider:
  after_layout:


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/